controller_manager:
  ros__parameters:
    update_rate: 30
    # use_sim_time: true

    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_cont:
  ros__parameters:

    publish_rate: 50.0
    base_frame_id: base_link

    left_wheel_names: ["l_wheel_joint"]
    right_wheel_names: ["r_wheel_joint"]
    wheel_separation: 0.38856
    wheel_radius: 0.04
    
    enable_odom_tf: true
    odom_frame_id: odom

    use_stamped_vel: false

    # # --- LIMITS SECTION (Uncommented and Updated) ---
    
    # # 1. Enable Limits
    # linear.x.has_velocity_limits: true
    # linear.x.has_acceleration_limits: true   # Recommended to stop wheel slip!
    # linear.x.has_jerk_limits: false
    
    # # 2. Set Max Linear Speed (Meters per Second)
    # # Start with 0.2 m/s. Increase later if you want.
    linear.x.max_velocity: 0.3              
    linear.x.min_velocity: -0.3              # Reverse speed limit
    
    # # 3. Set Acceleration (Meters per Second squared)
    # # Lower = smoother start. Higher = jerky start.
    # linear.x.max_acceleration: 0.8
    # linear.x.min_acceleration: -0.8

    # # 4. Set Turning Speed (Radians per Second)
    # angular.z.has_velocity_limits: true
    # angular.z.has_acceleration_limits: true
    # angular.z.has_jerk_limits: false
    
    # # 1.0 rad/s is roughly 57 degrees per second (safe turn)
    # angular.z.max_velocity: 1.0
    # angular.z.min_velocity: -1.0
    # angular.z.max_acceleration: 1.5
    # angular.z.min_acceleration: -1.5