services:
  ros2:
    image: ghcr.io/xaatim/foxy/arm:v2
    container_name: suvfoxy
    working_dir: /home
    tty: true
    stdin_open: true
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    
    environment:
      serialNo: "BR100A-SN-0005"
      robotKey: "dhgxtuddj7aj1vw0l42iw"
      serverUrl: "https://api-beam-robotics.up.railway.app"
      PROJECT_DIR: "home"
    volumes:
      - /usr/local/cuda-10.2:/usr/local/cuda-10.2
      - /usr/lib/aarch64-linux-gnu:/usr/lib/aarch64-linux-gnu
      - /usr/lib/aarch64-linux-gnu/tegra:/usr/lib/aarch64-linux-gnu/tegra
    devices:
      - "/dev/video0:/dev/video0"
      - "/dev/input:/dev/input"
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    command: >
      bash -c "source /opt/ros/foxy/setup.bash &&
               colcon build &&
               source /home/install/setup.bash &&
               ros2 launch robot_kernel robot_control_launch.py &&
               exec bash"
