# name: Docker Image publisher

# on:
#   push

# jobs:
#   build_and_publish:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - name: build and push the image
#         run: | 
#           docker login --username xaatim --password ${{ secrets.SUV_ACCESSTOKEN}} ghcr.io
#           docker buildx build . -t ghcr.io/xaatim/suv:multi --platform linux/amd64,linux/arm64
#           docker push ghcr.io/xaatim/suv:multi